spring:
  application:
    name : gateway
#  datasource:
#    url: jdbc:mysql://47.107.155.58:3306/cloud_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: dubbo_test
#    password: Aa123456789!
#    filters: slf4j,wall,mergeStat
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *

# 网关不应该连接数据库，但是我的core包，没有做到可拔插，暂时保留
#mybatis-plus:
#  mapper-locations: classpath*:com/duteliang/**/mapping/*.xml
#  typeAliasesPackage: com.duteliang.*.repository.model
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: true # 配置的缓存的全局开关
#    lazyLoadingEnabled: true # 延时加载的开关
#    multipleResultSetsEnabled: true # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
zuul:
  routes:
    # 将 product 应用 --> myProduct/**
    # 默认是 product/**
    product:
      path: /myProduct/**
      serviceId: product
#      sensitiveHeaders :
    user:
      path: /myUser/**
      serviceId: user
  # 排除字段
#  ignored-patterns:
#    - /**/message/getMessage
  # 全局设置排除敏感字段（默认有三个：cookie..）
  sensitive-headers:


##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用