spring:
  application:
    name : config-server
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
#          basedir:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
